/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "cannon_constants.h"

namespace paradigm4 { namespace cannon {

const cannonConstants g_cannon_constants;

cannonConstants::cannonConstants() {
}

}} // namespace

