/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package paradigm4.cannon_proxy;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ItemStatus implements org.apache.thrift.TEnum {
  FOUND(0),
  NOT_FOUND(1),
  ERROR(2);

  private final int value;

  private ItemStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ItemStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return FOUND;
      case 1:
        return NOT_FOUND;
      case 2:
        return ERROR;
      default:
        return null;
    }
  }
}
