// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "Cannon.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::paradigm4::cannon;

class CannonHandler : virtual public CannonIf {
 public:
  CannonHandler() {
    // Your initialization goes here
  }

  void get(CannonResponse& _return, const std::vector<int64_t> & keys, const int32_t data_version) {
    // Your implementation goes here
    printf("get\n");
  }

  bool insert(const std::vector<CannonKV> & kvs, const int32_t data_version) {
    // Your implementation goes here
    printf("insert\n");
  }

  bool clear_data(const int32_t data_version) {
    // Your implementation goes here
    printf("clear_data\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<CannonHandler> handler(new CannonHandler());
  shared_ptr<TProcessor> processor(new CannonProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

