/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef cannon_CONSTANTS_H
#define cannon_CONSTANTS_H

#include "cannon_types.h"

namespace paradigm4 { namespace cannon {

class cannonConstants {
 public:
  cannonConstants();

};

extern const cannonConstants g_cannon_constants;

}} // namespace

#endif
