/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef cannon_TYPES_H
#define cannon_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>


namespace paradigm4 { namespace cannon {

struct ItemStatus {
  enum type {
    FOUND = 0,
    NOT_FOUND = 1,
    ERROR = 2
  };
};

extern const std::map<int, const char*> _ItemStatus_VALUES_TO_NAMES;

struct Status {
  enum type {
    OK = 0,
    PARTIAL_OK = 1,
    ERROR = 2
  };
};

extern const std::map<int, const char*> _Status_VALUES_TO_NAMES;

class ValueItem;

class CannonResponse;

class CannonKV;

typedef struct _ValueItem__isset {
  _ValueItem__isset() : status(false), value(false) {}
  bool status :1;
  bool value :1;
} _ValueItem__isset;

class ValueItem {
 public:

  ValueItem(const ValueItem&);
  ValueItem& operator=(const ValueItem&);
  ValueItem() : status((ItemStatus::type)0), value(0) {
  }

  virtual ~ValueItem() throw();
  ItemStatus::type status;
  double value;

  _ValueItem__isset __isset;

  void __set_status(const ItemStatus::type val);

  void __set_value(const double val);

  bool operator == (const ValueItem & rhs) const
  {
    if (!(status == rhs.status))
      return false;
    if (!(value == rhs.value))
      return false;
    return true;
  }
  bool operator != (const ValueItem &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ValueItem & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(ValueItem &a, ValueItem &b);

inline std::ostream& operator<<(std::ostream& out, const ValueItem& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _CannonResponse__isset {
  _CannonResponse__isset() : status(false), values(false) {}
  bool status :1;
  bool values :1;
} _CannonResponse__isset;

class CannonResponse {
 public:

  CannonResponse(const CannonResponse&);
  CannonResponse& operator=(const CannonResponse&);
  CannonResponse() : status((Status::type)0) {
  }

  virtual ~CannonResponse() throw();
  Status::type status;
  std::vector<ValueItem>  values;

  _CannonResponse__isset __isset;

  void __set_status(const Status::type val);

  void __set_values(const std::vector<ValueItem> & val);

  bool operator == (const CannonResponse & rhs) const
  {
    if (!(status == rhs.status))
      return false;
    if (!(values == rhs.values))
      return false;
    return true;
  }
  bool operator != (const CannonResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CannonResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(CannonResponse &a, CannonResponse &b);

inline std::ostream& operator<<(std::ostream& out, const CannonResponse& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _CannonKV__isset {
  _CannonKV__isset() : key(false), value(false) {}
  bool key :1;
  bool value :1;
} _CannonKV__isset;

class CannonKV {
 public:

  CannonKV(const CannonKV&);
  CannonKV& operator=(const CannonKV&);
  CannonKV() : key(0), value(0) {
  }

  virtual ~CannonKV() throw();
  int64_t key;
  double value;

  _CannonKV__isset __isset;

  void __set_key(const int64_t val);

  void __set_value(const double val);

  bool operator == (const CannonKV & rhs) const
  {
    if (!(key == rhs.key))
      return false;
    if (!(value == rhs.value))
      return false;
    return true;
  }
  bool operator != (const CannonKV &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CannonKV & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(CannonKV &a, CannonKV &b);

inline std::ostream& operator<<(std::ostream& out, const CannonKV& obj)
{
  obj.printTo(out);
  return out;
}

}} // namespace

#endif
