/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Cannon_H
#define Cannon_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "cannon_types.h"

namespace paradigm4 { namespace cannon {

#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class CannonIf {
 public:
  virtual ~CannonIf() {}
  virtual void get(CannonResponse& _return, const std::vector<int64_t> & keys, const int32_t data_version) = 0;
  virtual bool insert(const std::vector<CannonKV> & kvs, const int32_t data_version) = 0;
  virtual bool clear_data(const int32_t data_version) = 0;
};

class CannonIfFactory {
 public:
  typedef CannonIf Handler;

  virtual ~CannonIfFactory() {}

  virtual CannonIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(CannonIf* /* handler */) = 0;
};

class CannonIfSingletonFactory : virtual public CannonIfFactory {
 public:
  CannonIfSingletonFactory(const boost::shared_ptr<CannonIf>& iface) : iface_(iface) {}
  virtual ~CannonIfSingletonFactory() {}

  virtual CannonIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(CannonIf* /* handler */) {}

 protected:
  boost::shared_ptr<CannonIf> iface_;
};

class CannonNull : virtual public CannonIf {
 public:
  virtual ~CannonNull() {}
  void get(CannonResponse& /* _return */, const std::vector<int64_t> & /* keys */, const int32_t /* data_version */) {
    return;
  }
  bool insert(const std::vector<CannonKV> & /* kvs */, const int32_t /* data_version */) {
    bool _return = false;
    return _return;
  }
  bool clear_data(const int32_t /* data_version */) {
    bool _return = false;
    return _return;
  }
};

typedef struct _Cannon_get_args__isset {
  _Cannon_get_args__isset() : keys(false), data_version(false) {}
  bool keys :1;
  bool data_version :1;
} _Cannon_get_args__isset;

class Cannon_get_args {
 public:

  Cannon_get_args(const Cannon_get_args&);
  Cannon_get_args& operator=(const Cannon_get_args&);
  Cannon_get_args() : data_version(0) {
  }

  virtual ~Cannon_get_args() throw();
  std::vector<int64_t>  keys;
  int32_t data_version;

  _Cannon_get_args__isset __isset;

  void __set_keys(const std::vector<int64_t> & val);

  void __set_data_version(const int32_t val);

  bool operator == (const Cannon_get_args & rhs) const
  {
    if (!(keys == rhs.keys))
      return false;
    if (!(data_version == rhs.data_version))
      return false;
    return true;
  }
  bool operator != (const Cannon_get_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Cannon_get_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Cannon_get_pargs {
 public:


  virtual ~Cannon_get_pargs() throw();
  const std::vector<int64_t> * keys;
  const int32_t* data_version;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Cannon_get_result__isset {
  _Cannon_get_result__isset() : success(false) {}
  bool success :1;
} _Cannon_get_result__isset;

class Cannon_get_result {
 public:

  Cannon_get_result(const Cannon_get_result&);
  Cannon_get_result& operator=(const Cannon_get_result&);
  Cannon_get_result() {
  }

  virtual ~Cannon_get_result() throw();
  CannonResponse success;

  _Cannon_get_result__isset __isset;

  void __set_success(const CannonResponse& val);

  bool operator == (const Cannon_get_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Cannon_get_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Cannon_get_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Cannon_get_presult__isset {
  _Cannon_get_presult__isset() : success(false) {}
  bool success :1;
} _Cannon_get_presult__isset;

class Cannon_get_presult {
 public:


  virtual ~Cannon_get_presult() throw();
  CannonResponse* success;

  _Cannon_get_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Cannon_insert_args__isset {
  _Cannon_insert_args__isset() : kvs(false), data_version(false) {}
  bool kvs :1;
  bool data_version :1;
} _Cannon_insert_args__isset;

class Cannon_insert_args {
 public:

  Cannon_insert_args(const Cannon_insert_args&);
  Cannon_insert_args& operator=(const Cannon_insert_args&);
  Cannon_insert_args() : data_version(0) {
  }

  virtual ~Cannon_insert_args() throw();
  std::vector<CannonKV>  kvs;
  int32_t data_version;

  _Cannon_insert_args__isset __isset;

  void __set_kvs(const std::vector<CannonKV> & val);

  void __set_data_version(const int32_t val);

  bool operator == (const Cannon_insert_args & rhs) const
  {
    if (!(kvs == rhs.kvs))
      return false;
    if (!(data_version == rhs.data_version))
      return false;
    return true;
  }
  bool operator != (const Cannon_insert_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Cannon_insert_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Cannon_insert_pargs {
 public:


  virtual ~Cannon_insert_pargs() throw();
  const std::vector<CannonKV> * kvs;
  const int32_t* data_version;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Cannon_insert_result__isset {
  _Cannon_insert_result__isset() : success(false) {}
  bool success :1;
} _Cannon_insert_result__isset;

class Cannon_insert_result {
 public:

  Cannon_insert_result(const Cannon_insert_result&);
  Cannon_insert_result& operator=(const Cannon_insert_result&);
  Cannon_insert_result() : success(0) {
  }

  virtual ~Cannon_insert_result() throw();
  bool success;

  _Cannon_insert_result__isset __isset;

  void __set_success(const bool val);

  bool operator == (const Cannon_insert_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Cannon_insert_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Cannon_insert_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Cannon_insert_presult__isset {
  _Cannon_insert_presult__isset() : success(false) {}
  bool success :1;
} _Cannon_insert_presult__isset;

class Cannon_insert_presult {
 public:


  virtual ~Cannon_insert_presult() throw();
  bool* success;

  _Cannon_insert_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Cannon_clear_data_args__isset {
  _Cannon_clear_data_args__isset() : data_version(false) {}
  bool data_version :1;
} _Cannon_clear_data_args__isset;

class Cannon_clear_data_args {
 public:

  Cannon_clear_data_args(const Cannon_clear_data_args&);
  Cannon_clear_data_args& operator=(const Cannon_clear_data_args&);
  Cannon_clear_data_args() : data_version(0) {
  }

  virtual ~Cannon_clear_data_args() throw();
  int32_t data_version;

  _Cannon_clear_data_args__isset __isset;

  void __set_data_version(const int32_t val);

  bool operator == (const Cannon_clear_data_args & rhs) const
  {
    if (!(data_version == rhs.data_version))
      return false;
    return true;
  }
  bool operator != (const Cannon_clear_data_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Cannon_clear_data_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Cannon_clear_data_pargs {
 public:


  virtual ~Cannon_clear_data_pargs() throw();
  const int32_t* data_version;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Cannon_clear_data_result__isset {
  _Cannon_clear_data_result__isset() : success(false) {}
  bool success :1;
} _Cannon_clear_data_result__isset;

class Cannon_clear_data_result {
 public:

  Cannon_clear_data_result(const Cannon_clear_data_result&);
  Cannon_clear_data_result& operator=(const Cannon_clear_data_result&);
  Cannon_clear_data_result() : success(0) {
  }

  virtual ~Cannon_clear_data_result() throw();
  bool success;

  _Cannon_clear_data_result__isset __isset;

  void __set_success(const bool val);

  bool operator == (const Cannon_clear_data_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Cannon_clear_data_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Cannon_clear_data_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Cannon_clear_data_presult__isset {
  _Cannon_clear_data_presult__isset() : success(false) {}
  bool success :1;
} _Cannon_clear_data_presult__isset;

class Cannon_clear_data_presult {
 public:


  virtual ~Cannon_clear_data_presult() throw();
  bool* success;

  _Cannon_clear_data_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class CannonClient : virtual public CannonIf {
 public:
  CannonClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  CannonClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void get(CannonResponse& _return, const std::vector<int64_t> & keys, const int32_t data_version);
  void send_get(const std::vector<int64_t> & keys, const int32_t data_version);
  void recv_get(CannonResponse& _return);
  bool insert(const std::vector<CannonKV> & kvs, const int32_t data_version);
  void send_insert(const std::vector<CannonKV> & kvs, const int32_t data_version);
  bool recv_insert();
  bool clear_data(const int32_t data_version);
  void send_clear_data(const int32_t data_version);
  bool recv_clear_data();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class CannonProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<CannonIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (CannonProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_get(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_insert(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_clear_data(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  CannonProcessor(boost::shared_ptr<CannonIf> iface) :
    iface_(iface) {
    processMap_["get"] = &CannonProcessor::process_get;
    processMap_["insert"] = &CannonProcessor::process_insert;
    processMap_["clear_data"] = &CannonProcessor::process_clear_data;
  }

  virtual ~CannonProcessor() {}
};

class CannonProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  CannonProcessorFactory(const ::boost::shared_ptr< CannonIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< CannonIfFactory > handlerFactory_;
};

class CannonMultiface : virtual public CannonIf {
 public:
  CannonMultiface(std::vector<boost::shared_ptr<CannonIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~CannonMultiface() {}
 protected:
  std::vector<boost::shared_ptr<CannonIf> > ifaces_;
  CannonMultiface() {}
  void add(boost::shared_ptr<CannonIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void get(CannonResponse& _return, const std::vector<int64_t> & keys, const int32_t data_version) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->get(_return, keys, data_version);
    }
    ifaces_[i]->get(_return, keys, data_version);
    return;
  }

  bool insert(const std::vector<CannonKV> & kvs, const int32_t data_version) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->insert(kvs, data_version);
    }
    return ifaces_[i]->insert(kvs, data_version);
  }

  bool clear_data(const int32_t data_version) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->clear_data(data_version);
    }
    return ifaces_[i]->clear_data(data_version);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class CannonConcurrentClient : virtual public CannonIf {
 public:
  CannonConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  CannonConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void get(CannonResponse& _return, const std::vector<int64_t> & keys, const int32_t data_version);
  int32_t send_get(const std::vector<int64_t> & keys, const int32_t data_version);
  void recv_get(CannonResponse& _return, const int32_t seqid);
  bool insert(const std::vector<CannonKV> & kvs, const int32_t data_version);
  int32_t send_insert(const std::vector<CannonKV> & kvs, const int32_t data_version);
  bool recv_insert(const int32_t seqid);
  bool clear_data(const int32_t data_version);
  int32_t send_clear_data(const int32_t data_version);
  bool recv_clear_data(const int32_t seqid);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif

}} // namespace

#endif
