/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Cannon_Service_H
#define Cannon_Service_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "proxy_types.h"

namespace paradigm4 { namespace cannon_proxy {

#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class Cannon_ServiceIf {
 public:
  virtual ~Cannon_ServiceIf() {}
  virtual void version(std::string& _return) = 0;
  virtual bool reload(const std::vector<std::string> & paths) = 0;
  virtual void get(CannonResponse& _return, const CannonRequest& req) = 0;
};

class Cannon_ServiceIfFactory {
 public:
  typedef Cannon_ServiceIf Handler;

  virtual ~Cannon_ServiceIfFactory() {}

  virtual Cannon_ServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(Cannon_ServiceIf* /* handler */) = 0;
};

class Cannon_ServiceIfSingletonFactory : virtual public Cannon_ServiceIfFactory {
 public:
  Cannon_ServiceIfSingletonFactory(const boost::shared_ptr<Cannon_ServiceIf>& iface) : iface_(iface) {}
  virtual ~Cannon_ServiceIfSingletonFactory() {}

  virtual Cannon_ServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(Cannon_ServiceIf* /* handler */) {}

 protected:
  boost::shared_ptr<Cannon_ServiceIf> iface_;
};

class Cannon_ServiceNull : virtual public Cannon_ServiceIf {
 public:
  virtual ~Cannon_ServiceNull() {}
  void version(std::string& /* _return */) {
    return;
  }
    bool reload(const std::vector<std::string> & /* paths */) {
    bool _return = false;
    return _return;
  }
  void get(CannonResponse& /* _return */, const CannonRequest& /* req */) {
    return;
  }
};


class Cannon_Service_version_args {
 public:

  Cannon_Service_version_args(const Cannon_Service_version_args&);
  Cannon_Service_version_args& operator=(const Cannon_Service_version_args&);
  Cannon_Service_version_args() {
  }

  virtual ~Cannon_Service_version_args() throw();

  bool operator == (const Cannon_Service_version_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Cannon_Service_version_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Cannon_Service_version_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Cannon_Service_version_pargs {
 public:


  virtual ~Cannon_Service_version_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Cannon_Service_version_result__isset {
  _Cannon_Service_version_result__isset() : success(false) {}
  bool success :1;
} _Cannon_Service_version_result__isset;

class Cannon_Service_version_result {
 public:

  Cannon_Service_version_result(const Cannon_Service_version_result&);
  Cannon_Service_version_result& operator=(const Cannon_Service_version_result&);
  Cannon_Service_version_result() : success() {
  }

  virtual ~Cannon_Service_version_result() throw();
  std::string success;

  _Cannon_Service_version_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const Cannon_Service_version_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Cannon_Service_version_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Cannon_Service_version_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Cannon_Service_version_presult__isset {
  _Cannon_Service_version_presult__isset() : success(false) {}
  bool success :1;
} _Cannon_Service_version_presult__isset;

class Cannon_Service_version_presult {
 public:


  virtual ~Cannon_Service_version_presult() throw();
  std::string* success;

  _Cannon_Service_version_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Cannon_Service_reload_args__isset {
  _Cannon_Service_reload_args__isset() : paths(false) {}
  bool paths :1;
} _Cannon_Service_reload_args__isset;

class Cannon_Service_reload_args {
 public:

  Cannon_Service_reload_args(const Cannon_Service_reload_args&);
  Cannon_Service_reload_args& operator=(const Cannon_Service_reload_args&);
  Cannon_Service_reload_args() {
  }

  virtual ~Cannon_Service_reload_args() throw();
  std::vector<std::string>  paths;

  _Cannon_Service_reload_args__isset __isset;

  void __set_paths(const std::vector<std::string> & val);

  bool operator == (const Cannon_Service_reload_args & rhs) const
  {
    if (!(paths == rhs.paths))
      return false;
    return true;
  }
  bool operator != (const Cannon_Service_reload_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Cannon_Service_reload_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Cannon_Service_reload_pargs {
 public:


  virtual ~Cannon_Service_reload_pargs() throw();
  const std::vector<std::string> * paths;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Cannon_Service_reload_result__isset {
  _Cannon_Service_reload_result__isset() : success(false) {}
  bool success :1;
} _Cannon_Service_reload_result__isset;

class Cannon_Service_reload_result {
 public:

  Cannon_Service_reload_result(const Cannon_Service_reload_result&);
  Cannon_Service_reload_result& operator=(const Cannon_Service_reload_result&);
  Cannon_Service_reload_result() : success(0) {
  }

  virtual ~Cannon_Service_reload_result() throw();
  bool success;

  _Cannon_Service_reload_result__isset __isset;

  void __set_success(const bool val);

  bool operator == (const Cannon_Service_reload_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Cannon_Service_reload_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Cannon_Service_reload_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Cannon_Service_reload_presult__isset {
  _Cannon_Service_reload_presult__isset() : success(false) {}
  bool success :1;
} _Cannon_Service_reload_presult__isset;

class Cannon_Service_reload_presult {
 public:


  virtual ~Cannon_Service_reload_presult() throw();
  bool* success;

  _Cannon_Service_reload_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Cannon_Service_get_args__isset {
  _Cannon_Service_get_args__isset() : req(false) {}
  bool req :1;
} _Cannon_Service_get_args__isset;

class Cannon_Service_get_args {
 public:

  Cannon_Service_get_args(const Cannon_Service_get_args&);
  Cannon_Service_get_args& operator=(const Cannon_Service_get_args&);
  Cannon_Service_get_args() {
  }

  virtual ~Cannon_Service_get_args() throw();
  CannonRequest req;

  _Cannon_Service_get_args__isset __isset;

  void __set_req(const CannonRequest& val);

  bool operator == (const Cannon_Service_get_args & rhs) const
  {
    if (!(req == rhs.req))
      return false;
    return true;
  }
  bool operator != (const Cannon_Service_get_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Cannon_Service_get_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Cannon_Service_get_pargs {
 public:


  virtual ~Cannon_Service_get_pargs() throw();
  const CannonRequest* req;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Cannon_Service_get_result__isset {
  _Cannon_Service_get_result__isset() : success(false) {}
  bool success :1;
} _Cannon_Service_get_result__isset;

class Cannon_Service_get_result {
 public:

  Cannon_Service_get_result(const Cannon_Service_get_result&);
  Cannon_Service_get_result& operator=(const Cannon_Service_get_result&);
  Cannon_Service_get_result() {
  }

  virtual ~Cannon_Service_get_result() throw();
  CannonResponse success;

  _Cannon_Service_get_result__isset __isset;

  void __set_success(const CannonResponse& val);

  bool operator == (const Cannon_Service_get_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Cannon_Service_get_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Cannon_Service_get_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Cannon_Service_get_presult__isset {
  _Cannon_Service_get_presult__isset() : success(false) {}
  bool success :1;
} _Cannon_Service_get_presult__isset;

class Cannon_Service_get_presult {
 public:


  virtual ~Cannon_Service_get_presult() throw();
  CannonResponse* success;

  _Cannon_Service_get_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class Cannon_ServiceClient : virtual public Cannon_ServiceIf {
 public:
  Cannon_ServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  Cannon_ServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void version(std::string& _return);
  void send_version();
  void recv_version(std::string& _return);
  bool reload(const std::vector<std::string> & paths);
  void send_reload(const std::vector<std::string> & paths);
  bool recv_reload();
  void get(CannonResponse& _return, const CannonRequest& req);
  void send_get(const CannonRequest& req);
  void recv_get(CannonResponse& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class Cannon_ServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<Cannon_ServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (Cannon_ServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_version(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_reload(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_get(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  Cannon_ServiceProcessor(boost::shared_ptr<Cannon_ServiceIf> iface) :
    iface_(iface) {
    processMap_["version"] = &Cannon_ServiceProcessor::process_version;
    processMap_["reload"] = &Cannon_ServiceProcessor::process_reload;
    processMap_["get"] = &Cannon_ServiceProcessor::process_get;
  }

  virtual ~Cannon_ServiceProcessor() {}
};

class Cannon_ServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  Cannon_ServiceProcessorFactory(const ::boost::shared_ptr< Cannon_ServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< Cannon_ServiceIfFactory > handlerFactory_;
};

class Cannon_ServiceMultiface : virtual public Cannon_ServiceIf {
 public:
  Cannon_ServiceMultiface(std::vector<boost::shared_ptr<Cannon_ServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~Cannon_ServiceMultiface() {}
 protected:
  std::vector<boost::shared_ptr<Cannon_ServiceIf> > ifaces_;
  Cannon_ServiceMultiface() {}
  void add(boost::shared_ptr<Cannon_ServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void version(std::string& _return) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->version(_return);
    }
    ifaces_[i]->version(_return);
    return;
  }

  bool reload(const std::vector<std::string> & paths) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->reload(paths);
    }
    return ifaces_[i]->reload(paths);
  }

  void get(CannonResponse& _return, const CannonRequest& req) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->get(_return, req);
    }
    ifaces_[i]->get(_return, req);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class Cannon_ServiceConcurrentClient : virtual public Cannon_ServiceIf {
 public:
  Cannon_ServiceConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  Cannon_ServiceConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void version(std::string& _return);
  int32_t send_version();
  void recv_version(std::string& _return, const int32_t seqid);
  bool reload(const std::vector<std::string> & paths);
  int32_t send_reload(const std::vector<std::string> & paths);
  bool recv_reload(const int32_t seqid);
  void get(CannonResponse& _return, const CannonRequest& req);
  int32_t send_get(const CannonRequest& req);
  void recv_get(CannonResponse& _return, const int32_t seqid);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif

}} // namespace

#endif
