/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "proxy_constants.h"

namespace paradigm4 { namespace cannon_proxy {

const proxyConstants g_proxy_constants;

proxyConstants::proxyConstants() {
}

}} // namespace

